spark-master:
        image: lahiru94/spark:latest
        command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
        hostname: spark-master
        # mem_limit: 600m
        environment:
                MASTER: spark://spark-master:7077
                SPARK_CONF_DIR: /conf
                SPARK_PUBLIC_DNS: 127.0.0.1
        expose:
                - 7001
                - 7002
                - 7003
                - 7004
                - 7005
                - 7006
                - 7077
                - 6066
        ports:
                - 5000:4040
                - 6066:6066
                - 7077:7077
                - 8080:8080
        volumes:
                - /opt/spark-docker/conf/master:/usr/local/spark-2.2.0-bin-hadoop2.7/conf
                - /opt/spark-docker/data:/spark-apps

spark-worker-1:
        image: lahiru94/spark:latest
        command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
        hostname: spark-worker-1
        mem_limit: 1g
        environment:
                MASTER: spark://spark-master:7077
                SPARK_CONF_DIR: /conf
                SPARK_PUBLIC_DNS: 127.0.0.1
                SPARK_WORKER_CORES: 2
                SPARK_WORKER_MEMORY: 512m
                SPARK_WORKER_PORT: 8088
                SPARK_WORKER_WEBUI_PORT: 8081
                SPARK_WORKER_INSTANCES: 1

        links:
                - spark-master
        expose:
                - 7012
                - 7013
                - 7014
                - 7015
                - 7016
                - 8088

        ports:
                - 8081:8081

        volumes:
                - /opt/spark-docker/conf/worker:/usr/local/spark-2.2.0-bin-hadoop2.7/conf
                - /opt/spark-docker/data:/spark-apps

#spark-worker-2:
#        image: lahiru94/spark:latest
#        command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
#        hostname: spark-worker-1
#        mem_limit: 600M
#        environment:
#                MASTER: spark://spark-master:7077
#                SPARK_CONF_DIR: /conf
#                SPARK_PUBLIC_DNS: 127.0.0.1
#                SPARK_WORKER_CORES: 1
#                SPARK_WORKER_MEMORY: 512m
#                SPARK_WORKER_PORT: 8088
#                SPARK_WORKER_WEBUI_PORT: 8082
#                SPARK_WORKER_INSTANCES: 1
#
#        links:
#                - spark-master
#        expose:
#                - 7012
#                - 7013
#                - 7014
#                - 7015
#                - 7016
#                - 8088
#
#        ports:
#                - 8082:8082
#
#        volumes:
#                - /opt/spark-docker/conf/worker:/usr/local/spark-2.2.0-bin-hadoop2.7/conf
#                - /opt/spark-docker/data:/spark-apps
